import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import { themeChange } from 'theme-change'
import Sidebar from '../layouts/sidebar'
import { Search } from '../components/modules'
import { Toggle } from '../components/elements'


const Home: NextPage = () => {

  useEffect(() => {
    themeChange(false)
    // 👆 false parameter is required for react project
  }, [])

  const [diretion, setDirection] = useState('ltr');

  return (
    <div dir={diretion} className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className='container mx-auto flex-row flex'>
        {/* Sidebar */}
        <Sidebar currentPage={"home"} />

        {/* Main */}
        <div className='pl-14 pt-4 w-4/5'>
          <div className='flex flex-row'>
            <Search />
            <div className="dropdown dropdown-hover z-10 relative">
              <label className="btn rounded-2xl bg-base-100 text-base-content hover:bg-secondary border-2 h-15 relative z-10 mb-4">Default theme</label>
              <ul className="dropdown-content menu p-2 shadow bg-base-100 w-52 border-2 rounded-2xl border-neutral">
                <li><a>Item 1</a></li>
                <li><a>Item 2</a></li>
              </ul>
              <div className='flex-none w-full mb-10 absolute t border-2 border-neutral rounded-2xl h-15 top-2 left-2 bg-secondary'>
              </div>
            </div>
            <Toggle />

          </div>
        </div>
      </div>


      {/* z-10 relative before:absolute before:top-2 before:border-neutral before:left-2 before:-z-10 before:border-2 before:rounded-2xl before:w-full before:h-full */}

      {/* <select data-choose-theme>
        <option value="">Default</option>
        <option value="dark">Dark</option>
        <option value="hp">hp</option>
        <option value="cupcake">mytheme</option>
      </select>
      <div className="group flex items-center">
        <div>sdfsdf</div>
        <div className="ltr:ml-20 rtl:mr-3">
          <p className="text-sm font-medium text-slate-700 group-hover:text-slate-900">hosseinhp</p>
          <p className="text-sm font-medium text-slate-500 group-hover:text-slate-700">hosseinppppppppppppppppp</p>
        </div>
      </div>

      <button onClick={() => { diretion === 'ltr' ? setDirection("rtl") : setDirection("ltr") }}>change direction</button> */}
    </div>
  )
}

export default Home
